title: Piast.Net
description: > # this means to ignore newlines until "baseurl:"
  Strona koła naukowego Piast.Net
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://piastdotnet.github.io/" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/img/icon-large.png"

social: 
  name: Your Facebook Page
  link: "https://www.facebook.com/piastnet"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_pages', '_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag


# Build settings
markdown: kramdown
permalink: pretty